//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppImportaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Producto
    {
        public int id { get; set; }
        public Nullable<int> fk_usuario { get; set; }
        public Nullable<int> fk_producto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
